In [1]:
import pandas as pd

In [2]:
df_books = pd.read_csv('./data/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')

In [4]:
df_books.head(20)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,30,2014,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction
11,A Patriot's History of the United States: From...,Larry Schweikart,4.6,460,2,2010,Non Fiction
12,A Stolen Life: A Memoir,Jaycee Dugard,4.6,4149,32,2011,Non Fiction
13,A Wrinkle in Time (Time Quintet),Madeleine L'Engle,4.5,5153,5,2018,Fiction
14,"Act Like a Lady, Think Like a Man: What Men Re...",Steve Harvey,4.6,5013,17,2009,Non Fiction
15,Adult Coloring Book Designs: Stress Relief Col...,Adult Coloring Book Designs,4.5,2313,4,2016,Non Fiction
16,Adult Coloring Book: Stress Relieving Animal D...,Blue Star Coloring,4.6,2925,6,2015,Non Fiction
17,Adult Coloring Book: Stress Relieving Patterns,Blue Star Coloring,4.4,2951,6,2015,Non Fiction
18,Adult Coloring Books: A Coloring Book for Adul...,Coloring Books for Adults,4.5,2426,8,2015,Non Fiction
19,Alexander Hamilton,Ron Chernow,4.8,9198,13,2016,Non Fiction

## Apply

In [5]:
# Definimos una función para ser aplicada

def two_times(value):
    return value * 2

In [6]:
# Usamos la función apply usando como argumento el nombre de la función (si realizar un call, o sea, sin paréntesis)
# Le aplica la función a cada uno de los valores que compone a las filas que posee la columna solicitada

df_books['User Rating'].apply(two_times)

0      9.4
1      9.2
2      9.4
3      9.4
4      9.6
      ...
545    9.8
546    9.4
547    9.4
548    9.4
549    9.4
Name: User Rating, Length: 550, dtype: float64

In [7]:
# Podemos usar apply para crear nuevas columnas

df_books['Rating 2'] = df_books['User Rating'].apply(two_times)

In [8]:
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating 2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,9.4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,9.2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,9.4
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,9.4
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,9.6
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,9.8
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,9.4
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,9.4
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,9.4
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,9.4

In [9]:
# También podemos usar lambda functions

df_books['Rating 3'] = df_books['User Rating'].apply(lambda x: x*3)

In [11]:
df_books.head(20)

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating 2,Rating 3
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,9.4,14.1
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,9.2,13.8
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,9.4,14.1
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,9.4,14.1
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,9.6,14.4
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction,8.8,13.2
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,30,2014,Fiction,9.4,14.1
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction,9.4,14.1
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction,9.4,14.1
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction,9.2,13.8
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction,9.2,13.8
11,A Patriot's History of the United States: From...,Larry Schweikart,4.6,460,2,2010,Non Fiction,9.2,13.8
12,A Stolen Life: A Memoir,Jaycee Dugard,4.6,4149,32,2011,Non Fiction,9.2,13.8
13,A Wrinkle in Time (Time Quintet),Madeleine L'Engle,4.5,5153,5,2018,Fiction,9.0,13.5
14,"Act Like a Lady, Think Like a Man: What Men Re...",Steve Harvey,4.6,5013,17,2009,Non Fiction,9.2,13.8
15,Adult Coloring Book Designs: Stress Relief Col...,Adult Coloring Book Designs,4.5,2313,4,2016,Non Fiction,9.0,13.5
16,Adult Coloring Book: Stress Relieving Animal D...,Blue Star Coloring,4.6,2925,6,2015,Non Fiction,9.2,13.8
17,Adult Coloring Book: Stress Relieving Patterns,Blue Star Coloring,4.4,2951,6,2015,Non Fiction,8.8,13.2
18,Adult Coloring Books: A Coloring Book for Adul...,Coloring Books for Adults,4.5,2426,8,2015,Non Fiction,9.0,13.5
19,Alexander Hamilton,Ron Chernow,4.8,9198,13,2016,Non Fiction,9.6,14.4

In [14]:
# Podemos usar distintas columnas para hacer nuestras operaciones
# Acá usamos una condición para aplicar la lambda function
# Lo que no tenemos que olvidar es especificar el eje al cual estamos referenciando
# Si no hacemos esto nos dará un error

df_books['Rating 4'] = df_books.apply(lambda x: x['User Rating'] * 2 if x['Genre'] == 'Fiction' else x['User Rating'], axis=1)

In [16]:
df_books.head(20)

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating 2,Rating 3,Rating 4
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,9.4,14.1,4.7
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,9.2,13.8,9.2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,9.4,14.1,4.7
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,9.4,14.1,9.4
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,9.6,14.4,4.8
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction,8.8,13.2,8.8
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,30,2014,Fiction,9.4,14.1,9.4
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction,9.4,14.1,9.4
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction,9.4,14.1,4.7
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction,9.2,13.8,9.2
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction,9.2,13.8,9.2
11,A Patriot's History of the United States: From...,Larry Schweikart,4.6,460,2,2010,Non Fiction,9.2,13.8,4.6
12,A Stolen Life: A Memoir,Jaycee Dugard,4.6,4149,32,2011,Non Fiction,9.2,13.8,4.6
13,A Wrinkle in Time (Time Quintet),Madeleine L'Engle,4.5,5153,5,2018,Fiction,9.0,13.5,9.0
14,"Act Like a Lady, Think Like a Man: What Men Re...",Steve Harvey,4.6,5013,17,2009,Non Fiction,9.2,13.8,4.6
15,Adult Coloring Book Designs: Stress Relief Col...,Adult Coloring Book Designs,4.5,2313,4,2016,Non Fiction,9.0,13.5,4.5
16,Adult Coloring Book: Stress Relieving Animal D...,Blue Star Coloring,4.6,2925,6,2015,Non Fiction,9.2,13.8,4.6
17,Adult Coloring Book: Stress Relieving Patterns,Blue Star Coloring,4.4,2951,6,2015,Non Fiction,8.8,13.2,4.4
18,Adult Coloring Books: A Coloring Book for Adul...,Coloring Books for Adults,4.5,2426,8,2015,Non Fiction,9.0,13.5,4.5
19,Alexander Hamilton,Ron Chernow,4.8,9198,13,2016,Non Fiction,9.6,14.4,4.8

### Ventajas de Apply

* Es mucho más rápido que hacerlo mediante for
* Es posible llamar a alguna api o recurso usando una funcion y de esa manera rellenar los datos